/**
 * Demo datasets behind the "Look inside" product screenshots.
 * Rows are trimmed samples — extend each `rows` array to lengthen the table.
 */
export const statusTone = {
  Approved: '#0FA36B', Pending: '#FF8A3D', Implementation: '#2F6BFF', 'Order approved': '#6A5AE0',
  Active: '#0FA36B', Termination: '#8B8595', Churned: '#9A94A6',
  Paid: '#0FA36B', Overdue: '#E23434', Draft: '#9A94A6', Sent: '#2F6BFF',
  Online: '#0FA36B', Offline: '#9A94A6', Suspended: '#E23434', Grace: '#FF8A3D',
  Open: '#2F6BFF', 'In progress': '#FF8A3D', Escalated: '#E23434', Resolved: '#0FA36B',
};

export const shots = [
  {
    label: 'Connect CRM',
    url: 'connect.div.app/connections',
    accent: '#FF0B55',
    action: 'New connection',
    searchHint: 'Search customers or circuit IDs',
    caption: 'Connect CRM — every link from commercial approval to active billing, in one pipeline.',
    nav: [['OV', 'Overview'], ['CN', 'Connections'], ['CU', 'Customers'], ['BL', 'Billing'], ['RP', 'Reports']],
    tableTitle: 'Connections',
    statusIdx: 4,
    grid: '1.3fr 2.2fr 0.8fr 1fr 1.1fr 0.8fr',
    cols: [
      { label: 'OID', align: 'left', mono: true },
      { label: 'CUSTOMER', align: 'left' },
      { label: 'SERVICE', align: 'left' },
      { label: 'BANDWIDTH', align: 'right', mono: true },
      { label: 'STATUS', align: 'left' },
      { label: 'TELCO', align: 'left' },
    ],
    kpis: [
      { label: 'Implementation', value: '119', sub: 'provisioning', filter: 'Implementation', tone: '#2F6BFF' },
      { label: 'Active links', value: '502', sub: 'live and billing', filter: 'Active', tone: '#0FA36B' },
      { label: 'Pending', value: '12', sub: 'awaiting sign-off', filter: 'Pending', tone: '#FF8A3D' },
      { label: 'Churned', value: '73', sub: 'disconnected FY', filter: 'Churned', tone: '#9A94A6' },
    ],
    rows: [
      ['FAB210920261B7W', 'VIBERNET DEMO INTERNET LTD', 'DNC', '155 Mbps', 'Approved', 'Airtel'],
      ['FAB20092026AKZ2', 'BHOMIKA DEMO NETWORK LTD', 'DNC', '500 Mbps', 'Approved', 'Airtel'],
      ['FAB200920261ZHZ', 'SYSWALL DEMO TELECOM LTD', 'DNC', '45 Mbps', 'Implementation', 'Airtel'],
      ['FAB190920264QK8', 'NORTHWIND DEMO MEDIA', 'Fibre', '880 Mbps', 'Implementation', 'Tata'],
      ['FAB180920269TR4', 'EASTGATE DEMO ENTERPRISES', 'Fibre', '1024 Mbps', 'Active', 'Airtel'],
      ['FAB170920261QD2', 'MERIDIAN DEMO TELELINE', 'Fibre', '750 Mbps', 'Active', 'Airtel'],
      ['FAB180920262XC9', 'PIXEL DEMO COMPUTE', 'DNC', '155 Mbps', 'Pending', 'Tata'],
      ['FAB150920264HS8', 'CEDARPOINT DEMO FOODS', 'Fibre', '150 Mbps', 'Churned', 'Jio'],
    ],
  },
  {
    label: 'BahiKhata',
    url: 'bahikhata.div.app/receivables',
    accent: '#B3341F',
    action: 'Onboard customer',
    searchHint: 'Search customers or managers',
    caption: 'BahiKhata — every rupee owed to you, aged by bucket and mapped to the manager who owns the chase.',
    nav: [['OV', 'Overview'], ['RC', 'Receivables'], ['PY', 'Payables'], ['LG', 'Ledger'], ['GS', 'GST']],
    tableTitle: 'All customers',
    statusIdx: -1,
    grid: '2fr 1.1fr 1fr 1fr 0.9fr',
    cols: [
      { label: 'CUSTOMER', align: 'left' },
      { label: 'MANAGER', align: 'left' },
      { label: 'TOTAL O/S', align: 'right', mono: true },
      { label: 'CURRENT', align: 'right', mono: true },
      { label: '90+', align: 'right', mono: true, tone: '#C22617' },
    ],
    kpis: [
      { label: 'Owed to you', value: '₹36,99,838', sub: '14 accounts', filter: 'All', tone: '#3F3A33' },
      { label: 'In terms', value: '79%', sub: 'current bucket', filter: 'All', tone: '#0FA36B' },
      { label: '90+ days', value: '₹5,70,221', sub: 'chase today', filter: '90+', tone: '#C22617' },
      { label: '30-60 days', value: '₹2,16,241', sub: 'watchlist', filter: 'All', tone: '#F2A600' },
    ],
    rows: [
      ['SKYLINE NETCOM DEMO PVT LTD', 'Demo Manager A', '₹1,94,640', '₹1,69,165', '₹25,475'],
      ['RIVERSIDE CABLE DEMO', 'Demo Manager A', '₹2,65,830', '₹2,65,830', '₹0'],
      ['WAVEGRID DEMO BROADBAND', 'Demo Manager B', '₹2,83,790', '₹49,194', '₹2,25,746'],
      ['NORTHWIND DEMO MEDIA', 'Demo Manager B', '₹4,12,300', '₹1,72,300', '₹1,60,000'],
      ['MERIDIAN DEMO TELELINE', 'Demo Manager B', '₹5,60,118', '₹5,60,118', '₹0'],
      ['ORBIT DEMO TELECOM', 'Demo Manager C', '₹8,41,905', '₹7,96,905', '₹0'],
      ['LAKEVIEW DEMO DIAGNOSTICS', 'Demo Manager C', '₹2,05,470', '₹41,470', '₹1,12,000'],
      ['CEDARPOINT DEMO FOODS', 'Demo Manager D', '₹78,940', '₹31,940', '₹47,000'],
    ],
  },
  {
    label: 'InvoicePro',
    url: 'invoicepro.div.app/invoices',
    accent: '#0FA36B',
    action: 'New invoice',
    searchHint: 'Search invoices or clients',
    caption: 'InvoicePro — outstanding, billed and drafted across the financial year at a glance.',
    nav: [['OV', 'Overview'], ['IN', 'Invoices'], ['QT', 'Quotes'], ['CL', 'Clients'], ['TX', 'Tax']],
    tableTitle: 'Invoices',
    statusIdx: 4,
    grid: '1fr 2fr 0.9fr 1fr 1.1fr 0.9fr',
    cols: [
      { label: 'INVOICE', align: 'left', mono: true },
      { label: 'CLIENT', align: 'left' },
      { label: 'RAISED', align: 'left', mono: true },
      { label: 'AMOUNT', align: 'right', mono: true },
      { label: 'STATUS', align: 'left' },
      { label: 'GST', align: 'right', mono: true },
    ],
    kpis: [
      { label: 'Outstanding', value: '₹27.9L', sub: 'sent, unpaid', filter: 'Sent', tone: '#2F6BFF' },
      { label: 'Overdue', value: '₹9.4L', sub: 'chase list', filter: 'Overdue', tone: '#E23434' },
      { label: 'Paid (FY)', value: '₹3.62Cr', sub: 'realised', filter: 'Paid', tone: '#0FA36B' },
      { label: 'Drafts', value: '14', sub: 'not yet issued', filter: 'Draft', tone: '#9A94A6' },
    ],
    rows: [
      ['INV-2411', 'Northwind Media Networks', '01 Sep', '₹4,20,000', 'Sent', '18%'],
      ['INV-2414', 'Harbour Solutions Sales', '03 Sep', '₹1,36,000', 'Paid', '18%'],
      ['INV-2418', 'Pixel Compute', '06 Sep', '₹92,500', 'Overdue', '18%'],
      ['INV-2421', 'Eastgate Enterprises', '09 Sep', '₹2,70,000', 'Sent', '18%'],
      ['INV-2425', 'Baker Street Hotels', '11 Sep', '₹58,400', 'Draft', '—'],
      ['INV-2433', 'Orbit Telecommunications', '14 Sep', '₹8,40,000', 'Sent', '18%'],
      ['INV-2437', 'Silverline Logistics', '16 Sep', '₹1,10,000', 'Overdue', '18%'],
      ['INV-2444', 'Cedar Point Foods', '18 Sep', '₹3,02,000', 'Paid', '18%'],
    ],
  },
  {
    label: 'Bharat RADIUS',
    url: 'radius.div.app/subscribers',
    accent: '#2F6BFF',
    action: 'Add subscriber',
    searchHint: 'Search username or reseller',
    caption: 'Bharat RADIUS — reseller branches, site nodes and subscriber sessions on one multi-tenant portal.',
    nav: [['OV', 'Overview'], ['SB', 'Subscribers'], ['RS', 'Resellers'], ['NA', 'NAS'], ['PL', 'Plans']],
    tableTitle: 'Subscriber sessions',
    statusIdx: 4,
    grid: '1.1fr 1.5fr 1fr 1fr 1fr 0.9fr',
    cols: [
      { label: 'USERNAME', align: 'left', mono: true },
      { label: 'RESELLER', align: 'left' },
      { label: 'PLAN', align: 'left' },
      { label: 'SESSION', align: 'right', mono: true },
      { label: 'STATUS', align: 'left' },
      { label: 'DATA', align: 'right', mono: true },
    ],
    kpis: [
      { label: 'Online now', value: '8,412', sub: 'live sessions', filter: 'Online', tone: '#0FA36B' },
      { label: 'Grace period', value: '271', sub: 'expiring plans', filter: 'Grace', tone: '#FF8A3D' },
      { label: 'Suspended', value: '96', sub: 'non-payment', filter: 'Suspended', tone: '#E23434' },
      { label: 'Offline', value: '3,058', sub: 'no active session', filter: 'Offline', tone: '#9A94A6' },
    ],
    rows: [
      ['ktr_1042@div', 'Kothari Broadband', 'FUP 150 Mbps', '04:12:09', 'Online', '18.4 GB'],
      ['vsn_2210@div', 'Vision Netcom', 'Unlimited 200', '11:02:47', 'Online', '46.8 GB'],
      ['vsn_2247@div', 'Vision Netcom', 'FUP 50 Mbps', '—', 'Offline', '0 GB'],
      ['amt_3301@div', 'Amrit Telelinks', 'FUP 150 Mbps', '02:19:55', 'Grace', '9.6 GB'],
      ['amt_3346@div', 'Amrit Telelinks', 'Unlimited 300', '07:41:12', 'Online', '72.3 GB'],
      ['skn_4120@div', 'Sky Net Services', 'FUP 100 Mbps', '—', 'Suspended', '0 GB'],
      ['rjn_5011@div', 'Rajan Fibernet', 'Unlimited 200', '09:33:04', 'Online', '51.2 GB'],
      ['mgl_6042@div', 'Mangal Broadband', 'FUP 50 Mbps', '—', 'Offline', '0 GB'],
    ],
  },
  {
    label: 'Samadhan',
    url: 'samadhan.div.app/tickets',
    accent: '#FF8A3D',
    action: 'New ticket',
    searchHint: 'Search tickets or customers',
    caption: 'Samadhan — ticket load per agent, escalations and resolution time, live off the support desk.',
    nav: [['OV', 'Overview'], ['TK', 'Tickets'], ['FD', 'Field'], ['SL', 'SLA'], ['AG', 'Agents']],
    tableTitle: 'Tickets',
    statusIdx: 4,
    grid: '1fr 1.8fr 1fr 1fr 1.1fr 0.9fr',
    cols: [
      { label: 'TICKET', align: 'left', mono: true },
      { label: 'CUSTOMER', align: 'left' },
      { label: 'AGENT', align: 'left' },
      { label: 'SLA LEFT', align: 'right', mono: true },
      { label: 'STATUS', align: 'left' },
      { label: 'PRIORITY', align: 'left' },
    ],
    kpis: [
      { label: 'Open', value: '142', sub: 'unassigned + queued', filter: 'Open', tone: '#2F6BFF' },
      { label: 'In progress', value: '86', sub: 'agent working', filter: 'In progress', tone: '#FF8A3D' },
      { label: 'Escalated', value: '11', sub: 'SLA at risk', filter: 'Escalated', tone: '#E23434' },
      { label: 'Resolved today', value: '204', sub: 'avg 3h 12m', filter: 'Resolved', tone: '#0FA36B' },
    ],
    rows: [
      ['SM-8841', 'Northwind Media Networks', 'R. Iyer', '01:12', 'Escalated', 'P1'],
      ['SM-8845', 'Harbour Solutions Sales', 'K. Desai', '04:38', 'In progress', 'P2'],
      ['SM-8849', 'Pixel Compute', 'A. Bhatt', '08:05', 'Open', 'P3'],
      ['SM-8853', 'Eastgate Enterprises', 'R. Iyer', '00:44', 'Escalated', 'P1'],
      ['SM-8857', 'Baker Street Hotels', 'S. Menon', '—', 'Resolved', 'P3'],
      ['SM-8865', 'Orbit Telecommunications', 'A. Bhatt', '12:00', 'Open', 'P3'],
      ['SM-8881', 'Lakeview Diagnostics', 'A. Bhatt', '01:58', 'In progress', 'P1'],
      ['SM-8885', 'Anand Motors Group', 'S. Menon', '—', 'Resolved', 'P2'],
    ],
  },
];
