export const siteConfig = {
  name: 'DIV',
  legalName: 'Development Innovation Vector Private Limited',
  shortName: 'DIV',
  url: 'https://thediv.in',
  locale: 'en_IN',
  foundingYear: 2026,
  tagline: 'We build your software, then we run it, for years',
  description:
    'Managed software development in India: DIV designs, builds, hosts and monitors CRM, billing, support and mobile systems — one team, for years after launch.',
  // Generated by app/og/route.jsx — always exists, no static file needed.
  ogImage: '/og',
  logo: '/core/DIV-Development-Innovation-Vector-logo.avif',
  googleSiteVerification: 'efaBcbhTZch0n3sWNIxNX4hHln80syfiUwHryFpA40g',
  keywords: [
    'managed software development services India',
    'custom software development company India',
    'enterprise software engineering',
    'cloud native deployments',
    'API-driven backend development',
    'microservices architecture',
    'MongoDB Atlas and Appwrite development',
    'software company Noida',
  ],

  // N.A.P. — must match the Google Business Profile character for character.
  phone: '+91 98996 80505',
  phoneHref: '+919899680505',
  whatsapp: '919899680505',
  email: 'info@thediv.in',
  hours: { label: 'Open 24 hours, 7 days', schema: 'Mo-Su 00:00-23:59' },
  address: {
    street: 'C6/28, Sector 31',
    city: 'Noida',
    region: 'Uttar Pradesh',
    postalCode: '201301',
    country: 'IN',
    countryName: 'India',
  },
  mapsUrl: 'https://www.google.com/maps/search/?api=1&query=C6%2F28%2C+Sector+31%2C+Noida%2C+Uttar+Pradesh+201301',
  sameAs: ['https://www.instagram.com/div__official_/'],
};

export const fullAddress = (a = siteConfig.address) =>
  `${a.street}, ${a.city}, ${a.region} ${a.postalCode}, ${a.countryName}`;
