export const siteConfig = {
  name: 'DIV',
  legalName: 'Development Innovation Vector Private Limited',
  shortName: 'DIV',
  url: 'https://thediv.in',
  locale: 'en_IN',
  tagline: 'We build your software, then we run it, for years',
  description:
    'Managed software development services in India. DIV designs, builds, hosts and monitors CRM, billing, support, network and mobile systems from its own data centre — one team, for years after launch.',
  ogImage: '/images/og-div-managed-software-development-india.jpg',
  googleSiteVerification: 'efaBcbhTZch0n3sWNIxNX4hHln80syfiUwHryFpA40g',
  keywords: [
    'managed software development services India',
    'custom software development company India',
    'enterprise software engineering',
    'custom CRM development India',
    'workflow automation',
    'cloud infrastructure and hosting India',
    'ISP billing and RADIUS software',
    'Next.js development company',
  ],
  phone: '+91-000-000-0000',
  email: 'hello@thediv.in',
  address: {
    street: 'Noida sector 31',
    city: 'Noida',
    region: 'Uttar Pradesh',
    postalCode: '201301',
    country: 'IN',
  },
  sameAs: ['https://www.linkedin.com/company/thediv', 'https://github.com/thediv'],
};